### PR TITLE
Support counting both entire match and specific group match

### PR DESCRIPTION
**Pull request by katat**

### CODE REVIEW

**Comment by katat** [comment]
That error is due to escaped strings automatically added by the CLI. Now the CLI should work for that regex.

I also added a test case for the regex to confirm the corresponding generated circuit also works.

**Comment by Divide-By-0** [comment]
Great! Looks like it passes now. Whats up with the "// todo TOFIX" section?

**Comment by Divide-By-0** [comment]
This code still doesn't have parity with the original code -- like your commented out test says, it doesn't seem to be able to handle the header regex.

```
zk-regex % yarn compile '+bh=(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|0|1|2|3|4|5|6|7|8|9|\\+|/|=)+; ' bh
yarn run v1.22.19
$ VERBOSE=1 node compiler/cli.js compile '+bh=(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|0|1|2|3|4|5|6|7|8|9|\\+|/|=)+; ' bh
/Users/aayushgupta/Documents/projects/zk-regex/node_modules/regexp-tree/dist/parser/generated/regexp-tree.js:627
    throw new SyntaxError(lineData + 'Unexpected token: "' + symbol + '" ' + ('at ' + line + ':' + column + '.'));
          ^

SyntaxError: 

/+bh=(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|0|1|2|3|4|5|6|7|8|9|\\+|/|=)+; /
 ^
Unexpected token: "+" at 1:1.
```

**Comment by katat** [comment]
This could be due to failure in the regex grammar check from `regexp-tree`. The error might indicate the header regex is not aligning with standard regex grammar, even though the generate circuit from it works?

To get the CLI works for this regex, the code of doing the check by using regexp-tree can be commented out.

**Comment by katat** [comment]
> How do you compile the header regex on a command line? I noticed your test for it was commented out as well.

The regex argument you pasted seem not to be completed 
```
'dkim-signature:((a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z)=(0|1|2|3|4|5|6|7|8|9|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|!|"|#|$|%|&|\'|\\(|\\)|\\*|\\+|,|-|.|/|:|<|=|>|\\?|@|[|\\\\|]|^|_|`|{|\\||}|~| |\t|\n|\r|\x0B|\f)+; )+bh=(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|0|1|2|3|4|5|6|7|8|9|\\+|/|=)+; ' bh
```

It is ended with `bh` that is not within a quote?

**Comment by katat** [comment]
> Whats up with the "// todo TOFIX" section?

In some regex, such as `1=(a|b) (2=(b|c)+ )+`, which doesn't have other characters appended the last group, the generate circuit seems no able to properly calculate the data points. But when it has something appended, such as `1=(a|b) (2=(b|c)+ )+d`, it works as expected. For now, I reckon this is an issue originating from the `lexical.js`.

**Comment by katat** [comment]
> How do you compile the header regex on a command line? I noticed your test for it was commented out as well.

Seems to be the same issue in automatically escaped arguments. Might need to figure out a way to entirely avoid escaping the argument string from the CLI.

**Comment by katat** [comment]
There are a couple of character escapes needed for the command you provided. Use the following command instead, which added necessary escapes needed.

```bash
yarn compile 'dkim-signature:((a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z)=(0|1|2|3|4|5|6|7|8|9|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|!|"|#|$|%|&|'\\\''|\\(|\\)|\\*|\\+|,|-|.|\/|:|<|=|>|\\?|@|\[|\\\\|\]|^|_|`|{|\\||}|~| |\t|\n|\r|\x0B|\f)+; )+bh=(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|0|1|2|3|4|5|6|7|8|9|\\+|\/|=)+; ' bh
```

There is also a test added for the sig header. Both the generated circuits are identical, even though the regex looks different from the one you provided, which doesn't align with the `regexp-tree` grammar check.

**Comment by katat** [comment]
I also updated the readme to describe the circuit in more details, which includes a link to my blog post explaining the theory behind the zk regex compiler.

**Comment by Divide-By-0** [comment]
Looks good! Excited for these circuits to be integrated back to the original repo.

**Pull request merged**
